# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

release_notes({
  'nl-NL' => "Diverse foutoplossingen en prestatie verbeteringen",
  'en-US' => "Various bug fixes and performance improvements."
})
